export const defaultCostConfiguration = {
    regrip: 10,
    wide: 1,
    double: 0,
    alpha: {
        "F": 0.5,
        "B": 3.5,
        "R": 0,
        "L": 2,
        "U": 0,
        "D": 2.5,
    },
    grip: {
        "F F": 0,
        "F U": 0,
        "F D": 0,
        "F Bd": 2,
        "F Bu": 2,
        "U F": 0,
        "U U": 1,
        "U D": 0.5,
        "U Bd": 2,
        "U Bu": 2,
        "D F": 0,
        "D U": 0.5,
        "D D": 1,
        "D Bd": 2,
        "D Bu": 2,
        "Bd F": 2,
        "Bd U": 2,
        "Bd D": 2,
        "Bd Bd": 3,
        "Bd Bu": 3,
        "Bu F": 2,
        "Bu U": 2,
        "Bu D": 2,
        "Bu Bd": 3,
        "Bu Bu": 3,
    },
    fingertrick: {
        "right_index": 0,
        "right_index_push": 1,
        "right_index_middle": 0,
        "right_ring": 1,
        "right_ring_middle": 1.5,
        "right_ring_push": 3,
        "right_up": 0,
        "right_up_double": 0,
        "right_down": 0,
        "right_down_double": 0,
        "left_index": 0,
        "left_index_push": 3,
        "left_index_middle": 0,
        "left_ring": 1,
        "left_ring_middle": 1.5,
        "left_ring_push": 3,
        "left_up": 0,
        "left_up_double": 0,
        "left_down": 0,
        "left_down_double": 0,
    }
}